from enum import StrEnum


class FileState(StrEnum):
    UPLOAD_PENDING = "UPLOAD_PENDING"

    UPLOADED_TO_QUARANTINE = "UPLOADED_TO_QUARANTINE"

    VIRUS_SCAN_PENDING = "VIRUS_SCAN_PENDING"
    VIRUS_SCAN_FAILED = "VIRUS_SCAN_FAILED"
    VIRUS_SCAN_PASSED = "VIRUS_SCAN_PASSED"

    ENCRYPTION_PENDING = "ENCRYPTION_PENDING"
    ENCRYPTED = "ENCRYPTED"

    STORAGE_PENDING = "STORAGE_PENDING"
    STORED = "STORED"

    ACTIVE = "ACTIVE"

    QUARANTINED = "QUARANTINED"

    DELETED = "DELETED"

    FAILED = "FAILED"
